const x = 20

try{
    x = 2
} catch (err) {
    console.log(`Erro: ${err}`)
}